# Generated by Django 5.2.7 on 2025-11-12 21:34

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peperoncino',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True)),
                ('family', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/peperoncini/')),
                ('scoville', models.PositiveIntegerField(help_text='Unità Scoville di piccantezza')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('shipping_name', models.CharField(max_length=255, verbose_name='Nome e Cognome Spedizione')),
                ('shipping_address', models.CharField(max_length=255, verbose_name='Indirizzo Spedizione')),
                ('shipping_city', models.CharField(max_length=100, verbose_name='Città Spedizione')),
                ('shipping_postal_code', models.CharField(max_length=20, verbose_name='Codice Postale Spedizione')),
                ('shipping_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono Spedizione')),
                ('status', models.CharField(choices=[('PENDING', 'In Attesa'), ('PROCESSING', 'In Elaborazione'), ('SHIPPED', 'Spedito'), ('DELIVERED', 'Consegnato'), ('CANCELLED', 'Cancellato')], default='PENDING', max_length=20, verbose_name='Stato Ordine')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('products', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImmaginePeperoncino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images/peperoncini/galleria/', verbose_name='File Immagine Secondaria')),
                ('ordine', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('peperoncino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleria', to='backend.peperoncino', verbose_name='Peperoncino Correlato')),
            ],
            options={
                'verbose_name': 'Immagine Secondaria',
                'verbose_name_plural': 'Immagini Secondarie',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('peperoncino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodotti', to='backend.peperoncino')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Indirizzo 1')),
                ('city', models.CharField(max_length=100, verbose_name='Città')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Codice Postale')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero di Telefono')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
        ),
    ]
