# Generated by Django 5.2.7 on 2025-11-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_province',
            field=models.CharField(default='UD', max_length=100, verbose_name='Provincia'),
            preserve_default=False,
        ),
    ]
