# Generated by Django 5.2.7 on 2025-11-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_order_shipping_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='province',
            field=models.CharField(default='UD', max_length=2, verbose_name='Provincia'),
            preserve_default=False,
        ),
    ]
